windshaft:
  build: .
  links:
    - db
  environment:
    - PGUSER=postgres
    - PGHOST=db
    - PGPASSWORD=password
db:
  image: mdillon/postgis:9.3
  expose:
    - "5432"
  environment:
    - POSTGRES_PASSWORD=password
  command: postgres
